name: Firebase Deploy

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  release_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.15.0"
      - run: npm ci
      - name: Build Webseite
        # Only to disable "treat warning as errors for now"
        run: npm run build
        env:
          CI: false
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.2.2
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
